name: Update JSON

on:
  pull_request:
    branches: [main]

jobs:
  update-json:
    if: github.actor == 'renovate[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: cachix/install-nix-action@v27
      - name: Run update script
        run: ./update.sh
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update versions.json"
          file_pattern: "versions.json"
